spring:
  application:
    name: edufy-recommendations-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/edufy-realm


jwt:
  auth:
    converter:
      resource-id:
        name: edufy-gateway-service
      principle-attribute: preferred_username

server:
  port: 4575

services:
  history:
    base-url: http://edufy-history-service:4595
  music:
    base-url:   http://edufy-music-service:4525
  pod:
    base-url:   http://edufy-pod-service:4535
  video:
    base-url:   http://edufy-video-service:4545
  ratings:
    base-url:   http://edufy-ratings-service:4585
  user:
    base-url: ${SERVICES_USER_BASE_URL:http://edufy-user-service:4515/users}

